name: Error
on: [push, workflow_dispatch]

jobs:
  error:
    runs-on: windows-latest
    concurrency:
      group: ${{ matrix.arguments }}
      cancel-in-progress: true
    strategy:
      matrix:
        arguments: ["", "foo", "bar"]
    steps:
      - run: |
          echo "Hello world"
