
name: Error
on: [push, workflow_dispatch]

jobs:
  runs-on: windows-latest
  error:
    concurrency:
      group: ${{ matrix.arguments }}
    strategy:
      matrix:
        arguments: ["foo", "bar"]
